name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial!
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Move files to root directory
        run: |
          mv dist/pacman-contribution-graph.svg .
          mv dist/pacman-contribution-graph-dark.svg .
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pacman-contribution-graph.svg pacman-contribution-graph-dark.svg
          git diff --staged --quiet || git commit -m "Update Pacman graph"
          git push
