name: Generate Animations
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (Pacman)
    - cron: "0 */6 * * *" # Runs every 6 hours (Snake)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Commit and push Pacman
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Update Pacman graph"
          git pull --rebase origin main  # Add this line
          git push
